### ISSUE TITLE
Migrate code and development issues from sensor-group

### ISSUE THREAD

**Issue by davclark** [glass-bead-labs/data-connector#1]
On issues, look for the "issue-tracker" tag. You can link to them or copy them to this issue tracker.

**Comment by postfalk** [comment]
We should use something like this http://www.jejik.com/articles/2007/02/a_simple_unix_linux_daemon_in_python/.

**Comment by davclark** [comment]
I think it's way easier to write non-forking code and wrap it in a supervisor like [circus](http://circus.readthedocs.org/) or [supervisord](http://supervisord.org/), or like I said when I chatted you on Slack, even systemd. But this is likely another issue! And I don't want to micro-manage.

**Comment by davclark** [comment]
On the topic of migration - @KishPatel1996 and @dianecw, do you want to help with the migration of issues? I think you just want [these](/glass-bead-labs/sensor-group/labels/issue-tracker).

**Comment by KishPatel1996** [comment]
Migrated both issue threads to this repository using an external program called https://github-issue-mover.appspot.com/.  Seems to have done the job!

**Comment by davclark** [comment]
You should close issues when you complete them!
